/*
 * generated by Xtext
 */
package com.softicar.sqml.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSqmlScopeProvider extends DelegatingScopeProvider {
}
