/*
 * generated by Xtext
 */
package com.softicar.sqml.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.softicar.sqml.services.SqmlGrammarAccess;

public class SqmlParser extends AbstractContentAssistParser {
	
	@Inject
	private SqmlGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.softicar.sqml.ui.contentassist.antlr.internal.InternalSqmlParser createParser() {
		com.softicar.sqml.ui.contentassist.antlr.internal.InternalSqmlParser result = new com.softicar.sqml.ui.contentassist.antlr.internal.InternalSqmlParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSqmlFileElementAccess().getAlternatives(), "rule__SqmlFileElement__Alternatives");
					put(grammarAccess.getSqmlTableColumnAccess().getAlternatives_3_1(), "rule__SqmlTableColumn__Alternatives_3_1");
					put(grammarAccess.getSqmlTableRowValueAccess().getAlternatives(), "rule__SqmlTableRowValue__Alternatives");
					put(grammarAccess.getSqmlDefaultValueAccess().getAlternatives(), "rule__SqmlDefaultValue__Alternatives");
					put(grammarAccess.getSqmlTableKeyAccess().getAlternatives_0(), "rule__SqmlTableKey__Alternatives_0");
					put(grammarAccess.getSqmlFunctionAccess().getAlternatives_7(), "rule__SqmlFunction__Alternatives_7");
					put(grammarAccess.getSqmlSqlTokenAccess().getAlternatives(), "rule__SqmlSqlToken__Alternatives");
					put(grammarAccess.getSqmlSqlKeywordAccess().getKeywordTextAlternatives_0(), "rule__SqmlSqlKeyword__KeywordTextAlternatives_0");
					put(grammarAccess.getSqmlSqlSymbolAccess().getSymbolTextAlternatives_0(), "rule__SqmlSqlSymbol__SymbolTextAlternatives_0");
					put(grammarAccess.getSqmlSqlNumberLiteralAccess().getAlternatives(), "rule__SqmlSqlNumberLiteral__Alternatives");
					put(grammarAccess.getSqmlSelectPartAccess().getAlternatives(), "rule__SqmlSelectPart__Alternatives");
					put(grammarAccess.getSqmlFromClauseAccess().getVariableAlternatives_1_0(), "rule__SqmlFromClause__VariableAlternatives_1_0");
					put(grammarAccess.getSqmlJoinClauseAccess().getVariableAlternatives_2_0(), "rule__SqmlJoinClause__VariableAlternatives_2_0");
					put(grammarAccess.getSqmlOrderByExpressionAccess().getAlternatives_1(), "rule__SqmlOrderByExpression__Alternatives_1");
					put(grammarAccess.getSqmlConditionAccess().getAlternatives(), "rule__SqmlCondition__Alternatives");
					put(grammarAccess.getSqmlConditionAccess().getAlternatives_2_1(), "rule__SqmlCondition__Alternatives_2_1");
					put(grammarAccess.getSqmlConditionAccess().getRightAlternatives_2_1_4_3_0(), "rule__SqmlCondition__RightAlternatives_2_1_4_3_0");
					put(grammarAccess.getSqmlPrimayAccess().getAlternatives(), "rule__SqmlPrimay__Alternatives");
					put(grammarAccess.getSqmlStaticAtomAccess().getAlternatives(), "rule__SqmlStaticAtom__Alternatives");
					put(grammarAccess.getSqmlLiteralAccess().getAlternatives(), "rule__SqmlLiteral__Alternatives");
					put(grammarAccess.getSqmlBooleanLiteralAccess().getAlternatives(), "rule__SqmlBooleanLiteral__Alternatives");
					put(grammarAccess.getSqmlFunctionNameAccess().getAlternatives(), "rule__SqmlFunctionName__Alternatives");
					put(grammarAccess.getSqmlComparisonOperatorAccess().getAlternatives(), "rule__SqmlComparisonOperator__Alternatives");
					put(grammarAccess.getSqmlAdditionOperatorAccess().getAlternatives(), "rule__SqmlAdditionOperator__Alternatives");
					put(grammarAccess.getSqmlMultiplicationOperatorAccess().getAlternatives(), "rule__SqmlMultiplicationOperator__Alternatives");
					put(grammarAccess.getSqmlForeignKeyActionAccess().getAlternatives(), "rule__SqmlForeignKeyAction__Alternatives");
					put(grammarAccess.getSqmlFileAccess().getGroup(), "rule__SqmlFile__Group__0");
					put(grammarAccess.getSqmlPackageDeclarationAccess().getGroup(), "rule__SqmlPackageDeclaration__Group__0");
					put(grammarAccess.getSqmlImportAccess().getGroup(), "rule__SqmlImport__Group__0");
					put(grammarAccess.getSqmlTypeReferenceAccess().getGroup(), "rule__SqmlTypeReference__Group__0");
					put(grammarAccess.getSqmlTypeReferenceAccess().getGroup_1(), "rule__SqmlTypeReference__Group_1__0");
					put(grammarAccess.getSqmlTypeReferenceAccess().getGroup_1_2(), "rule__SqmlTypeReference__Group_1_2__0");
					put(grammarAccess.getSqmlTypeReferenceAccess().getGroup_2(), "rule__SqmlTypeReference__Group_2__0");
					put(grammarAccess.getSqmlValueTypeAccess().getGroup(), "rule__SqmlValueType__Group__0");
					put(grammarAccess.getSqmlEnumAccess().getGroup(), "rule__SqmlEnum__Group__0");
					put(grammarAccess.getSqmlEnumAccess().getGroup_2(), "rule__SqmlEnum__Group_2__0");
					put(grammarAccess.getSqmlEnumeratorAccess().getGroup(), "rule__SqmlEnumerator__Group__0");
					put(grammarAccess.getSqmlEnumeratorAccess().getGroup_1(), "rule__SqmlEnumerator__Group_1__0");
					put(grammarAccess.getSqmlTableAccess().getGroup(), "rule__SqmlTable__Group__0");
					put(grammarAccess.getSqmlTableColumnAccess().getGroup(), "rule__SqmlTableColumn__Group__0");
					put(grammarAccess.getSqmlTableColumnAccess().getGroup_3(), "rule__SqmlTableColumn__Group_3__0");
					put(grammarAccess.getSqmlTableColumnAccess().getGroup_4(), "rule__SqmlTableColumn__Group_4__0");
					put(grammarAccess.getSqmlTableColumnAccess().getGroup_4_1_3(), "rule__SqmlTableColumn__Group_4_1_3__0");
					put(grammarAccess.getSqmlTableColumnAccess().getGroup_4_1_4(), "rule__SqmlTableColumn__Group_4_1_4__0");
					put(grammarAccess.getSqmlTableColumnAccess().getGroup_4_1_5(), "rule__SqmlTableColumn__Group_4_1_5__0");
					put(grammarAccess.getSqmlTableColumnAccess().getGroup_4_1_7(), "rule__SqmlTableColumn__Group_4_1_7__0");
					put(grammarAccess.getSqmlTableColumnAccess().getGroup_4_1_8(), "rule__SqmlTableColumn__Group_4_1_8__0");
					put(grammarAccess.getSqmlTableColumnAccess().getGroup_4_1_9(), "rule__SqmlTableColumn__Group_4_1_9__0");
					put(grammarAccess.getSqmlTableColumnAccess().getGroup_4_1_10(), "rule__SqmlTableColumn__Group_4_1_10__0");
					put(grammarAccess.getSqmlTableColumnAccess().getGroup_4_1_11(), "rule__SqmlTableColumn__Group_4_1_11__0");
					put(grammarAccess.getSqmlTableColumnAccess().getGroup_4_1_12(), "rule__SqmlTableColumn__Group_4_1_12__0");
					put(grammarAccess.getSqmlTableColumnAccess().getGroup_4_1_13(), "rule__SqmlTableColumn__Group_4_1_13__0");
					put(grammarAccess.getSqmlTableColumnAccess().getGroup_4_1_14(), "rule__SqmlTableColumn__Group_4_1_14__0");
					put(grammarAccess.getSqmlTableRowAccess().getGroup(), "rule__SqmlTableRow__Group__0");
					put(grammarAccess.getSqmlTableRowAccess().getGroup_3(), "rule__SqmlTableRow__Group_3__0");
					put(grammarAccess.getSqmlRowConstructorDefaultValueAccess().getGroup(), "rule__SqmlRowConstructorDefaultValue__Group__0");
					put(grammarAccess.getSqmlRowConstructorDefaultValueAccess().getGroup_2(), "rule__SqmlRowConstructorDefaultValue__Group_2__0");
					put(grammarAccess.getSqmlRowConstructorDefaultValueAccess().getGroup_2_1(), "rule__SqmlRowConstructorDefaultValue__Group_2_1__0");
					put(grammarAccess.getSqmlLiteralDefaultValueAccess().getGroup(), "rule__SqmlLiteralDefaultValue__Group__0");
					put(grammarAccess.getSqmlTableKeyAccess().getGroup(), "rule__SqmlTableKey__Group__0");
					put(grammarAccess.getSqmlTableKeyAccess().getGroup_0_0(), "rule__SqmlTableKey__Group_0_0__0");
					put(grammarAccess.getSqmlTableKeyAccess().getGroup_0_1(), "rule__SqmlTableKey__Group_0_1__0");
					put(grammarAccess.getSqmlTableKeyAccess().getGroup_2(), "rule__SqmlTableKey__Group_2__0");
					put(grammarAccess.getSqmlQueryAccess().getGroup(), "rule__SqmlQuery__Group__0");
					put(grammarAccess.getSqmlQueryParameterAccess().getGroup(), "rule__SqmlQueryParameter__Group__0");
					put(grammarAccess.getSqmlFunctionAccess().getGroup(), "rule__SqmlFunction__Group__0");
					put(grammarAccess.getSqmlFunctionAccess().getGroup_4(), "rule__SqmlFunction__Group_4__0");
					put(grammarAccess.getSqmlFunctionAccess().getGroup_4_1(), "rule__SqmlFunction__Group_4_1__0");
					put(grammarAccess.getSqmlFunctionAccess().getGroup_7_1(), "rule__SqmlFunction__Group_7_1__0");
					put(grammarAccess.getSqmlFunctionParameterAccess().getGroup(), "rule__SqmlFunctionParameter__Group__0");
					put(grammarAccess.getSqmlSqlAccess().getGroup(), "rule__SqmlSql__Group__0");
					put(grammarAccess.getSqmlSelectIfAccess().getGroup(), "rule__SqmlSelectIf__Group__0");
					put(grammarAccess.getSqmlSelectElseIfAccess().getGroup(), "rule__SqmlSelectElseIf__Group__0");
					put(grammarAccess.getSqmlSelectElseAccess().getGroup(), "rule__SqmlSelectElse__Group__0");
					put(grammarAccess.getSqmlSelectClauseAccess().getGroup(), "rule__SqmlSelectClause__Group__0");
					put(grammarAccess.getSqmlSelectClauseAccess().getGroup_3(), "rule__SqmlSelectClause__Group_3__0");
					put(grammarAccess.getSqmlSelectColumnAccess().getGroup(), "rule__SqmlSelectColumn__Group__0");
					put(grammarAccess.getSqmlSelectColumnAccess().getGroup_1(), "rule__SqmlSelectColumn__Group_1__0");
					put(grammarAccess.getSqmlSelectColumnAccess().getGroup_2(), "rule__SqmlSelectColumn__Group_2__0");
					put(grammarAccess.getSqmlFromClauseAccess().getGroup(), "rule__SqmlFromClause__Group__0");
					put(grammarAccess.getSqmlForeignKeyVariableAccess().getGroup(), "rule__SqmlForeignKeyVariable__Group__0");
					put(grammarAccess.getSqmlTableVariableAccess().getGroup(), "rule__SqmlTableVariable__Group__0");
					put(grammarAccess.getSqmlSubSelectVariableAccess().getGroup(), "rule__SqmlSubSelectVariable__Group__0");
					put(grammarAccess.getSqmlJoinClauseAccess().getGroup(), "rule__SqmlJoinClause__Group__0");
					put(grammarAccess.getSqmlJoinClauseAccess().getGroup_3(), "rule__SqmlJoinClause__Group_3__0");
					put(grammarAccess.getSqmlWhereClauseAccess().getGroup(), "rule__SqmlWhereClause__Group__0");
					put(grammarAccess.getSqmlGroupByClauseAccess().getGroup(), "rule__SqmlGroupByClause__Group__0");
					put(grammarAccess.getSqmlGroupByClauseAccess().getGroup_3(), "rule__SqmlGroupByClause__Group_3__0");
					put(grammarAccess.getSqmlHavingClauseAccess().getGroup(), "rule__SqmlHavingClause__Group__0");
					put(grammarAccess.getSqmlOrderByClauseAccess().getGroup(), "rule__SqmlOrderByClause__Group__0");
					put(grammarAccess.getSqmlOrderByClauseAccess().getGroup_3(), "rule__SqmlOrderByClause__Group_3__0");
					put(grammarAccess.getSqmlOrderByExpressionAccess().getGroup(), "rule__SqmlOrderByExpression__Group__0");
					put(grammarAccess.getSqmlOrAccess().getGroup(), "rule__SqmlOr__Group__0");
					put(grammarAccess.getSqmlOrAccess().getGroup_1(), "rule__SqmlOr__Group_1__0");
					put(grammarAccess.getSqmlAndAccess().getGroup(), "rule__SqmlAnd__Group__0");
					put(grammarAccess.getSqmlAndAccess().getGroup_1(), "rule__SqmlAnd__Group_1__0");
					put(grammarAccess.getSqmlConditionAccess().getGroup_0(), "rule__SqmlCondition__Group_0__0");
					put(grammarAccess.getSqmlConditionAccess().getGroup_1(), "rule__SqmlCondition__Group_1__0");
					put(grammarAccess.getSqmlConditionAccess().getGroup_2(), "rule__SqmlCondition__Group_2__0");
					put(grammarAccess.getSqmlConditionAccess().getGroup_2_1_0(), "rule__SqmlCondition__Group_2_1_0__0");
					put(grammarAccess.getSqmlConditionAccess().getGroup_2_1_1(), "rule__SqmlCondition__Group_2_1_1__0");
					put(grammarAccess.getSqmlConditionAccess().getGroup_2_1_1_4(), "rule__SqmlCondition__Group_2_1_1_4__0");
					put(grammarAccess.getSqmlConditionAccess().getGroup_2_1_2(), "rule__SqmlCondition__Group_2_1_2__0");
					put(grammarAccess.getSqmlConditionAccess().getGroup_2_1_3(), "rule__SqmlCondition__Group_2_1_3__0");
					put(grammarAccess.getSqmlConditionAccess().getGroup_2_1_4(), "rule__SqmlCondition__Group_2_1_4__0");
					put(grammarAccess.getSqmlConditionAccess().getGroup_2_1_5(), "rule__SqmlCondition__Group_2_1_5__0");
					put(grammarAccess.getSqmlAdditionAccess().getGroup(), "rule__SqmlAddition__Group__0");
					put(grammarAccess.getSqmlAdditionAccess().getGroup_1(), "rule__SqmlAddition__Group_1__0");
					put(grammarAccess.getSqmlMultiplicationAccess().getGroup(), "rule__SqmlMultiplication__Group__0");
					put(grammarAccess.getSqmlMultiplicationAccess().getGroup_1(), "rule__SqmlMultiplication__Group_1__0");
					put(grammarAccess.getSqmlSubSelectAccess().getGroup(), "rule__SqmlSubSelect__Group__0");
					put(grammarAccess.getSqmlStaticVariableReferenceAccess().getGroup(), "rule__SqmlStaticVariableReference__Group__0");
					put(grammarAccess.getSqmlRowConstructorAccess().getGroup(), "rule__SqmlRowConstructor__Group__0");
					put(grammarAccess.getSqmlRowConstructorAccess().getGroup_3(), "rule__SqmlRowConstructor__Group_3__0");
					put(grammarAccess.getSqmlNegationAccess().getGroup(), "rule__SqmlNegation__Group__0");
					put(grammarAccess.getSqmlFunctionCallAccess().getGroup(), "rule__SqmlFunctionCall__Group__0");
					put(grammarAccess.getSqmlFunctionCallAccess().getGroup_2(), "rule__SqmlFunctionCall__Group_2__0");
					put(grammarAccess.getSqmlFunctionCallAccess().getGroup_2_1(), "rule__SqmlFunctionCall__Group_2_1__0");
					put(grammarAccess.getSqmlGroupConcatAccess().getGroup(), "rule__SqmlGroupConcat__Group__0");
					put(grammarAccess.getSqmlGroupConcatAccess().getGroup_4(), "rule__SqmlGroupConcat__Group_4__0");
					put(grammarAccess.getSqmlGroupConcatAccess().getGroup_5(), "rule__SqmlGroupConcat__Group_5__0");
					put(grammarAccess.getSqmlGroupConcatAccess().getGroup_5_3(), "rule__SqmlGroupConcat__Group_5_3__0");
					put(grammarAccess.getSqmlGroupConcatAccess().getGroup_6(), "rule__SqmlGroupConcat__Group_6__0");
					put(grammarAccess.getSqmlCaseAccess().getGroup(), "rule__SqmlCase__Group__0");
					put(grammarAccess.getSqmlCaseAccess().getGroup_3(), "rule__SqmlCase__Group_3__0");
					put(grammarAccess.getSqmlCaseWhenAccess().getGroup(), "rule__SqmlCaseWhen__Group__0");
					put(grammarAccess.getSqmlIfAccess().getGroup(), "rule__SqmlIf__Group__0");
					put(grammarAccess.getSqmlIfNullAccess().getGroup(), "rule__SqmlIfNull__Group__0");
					put(grammarAccess.getSqmlStaticIfAccess().getGroup(), "rule__SqmlStaticIf__Group__0");
					put(grammarAccess.getSqmlStaticIfAccess().getGroup_6(), "rule__SqmlStaticIf__Group_6__0");
					put(grammarAccess.getSqmlStaticIfAccess().getGroup_6_0(), "rule__SqmlStaticIf__Group_6_0__0");
					put(grammarAccess.getSqmlStaticIfAccess().getGroup_6_0_0(), "rule__SqmlStaticIf__Group_6_0_0__0");
					put(grammarAccess.getSqmlStaticIfAccess().getGroup_7(), "rule__SqmlStaticIf__Group_7__0");
					put(grammarAccess.getSqmlStaticOrAccess().getGroup(), "rule__SqmlStaticOr__Group__0");
					put(grammarAccess.getSqmlStaticOrAccess().getGroup_1(), "rule__SqmlStaticOr__Group_1__0");
					put(grammarAccess.getSqmlStaticAndAccess().getGroup(), "rule__SqmlStaticAnd__Group__0");
					put(grammarAccess.getSqmlStaticAndAccess().getGroup_1(), "rule__SqmlStaticAnd__Group_1__0");
					put(grammarAccess.getSqmlStaticIsEmptyAccess().getGroup(), "rule__SqmlStaticIsEmpty__Group__0");
					put(grammarAccess.getSqmlStaticIsNullAccess().getGroup(), "rule__SqmlStaticIsNull__Group__0");
					put(grammarAccess.getSqmlStaticIsTrueAccess().getGroup(), "rule__SqmlStaticIsTrue__Group__0");
					put(grammarAccess.getSqmlStaticParenthesesAccess().getGroup(), "rule__SqmlStaticParentheses__Group__0");
					put(grammarAccess.getSqmlValueReferenceAccess().getGroup(), "rule__SqmlValueReference__Group__0");
					put(grammarAccess.getSqmlPathAccess().getGroup(), "rule__SqmlPath__Group__0");
					put(grammarAccess.getSqmlPathAccess().getGroup_1(), "rule__SqmlPath__Group_1__0");
					put(grammarAccess.getSqmlBooleanLiteralAccess().getGroup_0(), "rule__SqmlBooleanLiteral__Group_0__0");
					put(grammarAccess.getSqmlBooleanLiteralAccess().getGroup_1(), "rule__SqmlBooleanLiteral__Group_1__0");
					put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getSqmlFileAccess().getPackageDeclarationAssignment_0(), "rule__SqmlFile__PackageDeclarationAssignment_0");
					put(grammarAccess.getSqmlFileAccess().getImportsAssignment_1(), "rule__SqmlFile__ImportsAssignment_1");
					put(grammarAccess.getSqmlFileAccess().getElementsAssignment_2(), "rule__SqmlFile__ElementsAssignment_2");
					put(grammarAccess.getSqmlPackageDeclarationAccess().getNameAssignment_1(), "rule__SqmlPackageDeclaration__NameAssignment_1");
					put(grammarAccess.getSqmlImportAccess().getTargetAssignment_1(), "rule__SqmlImport__TargetAssignment_1");
					put(grammarAccess.getSqmlTypeReferenceAccess().getTypeDefinitionAssignment_0(), "rule__SqmlTypeReference__TypeDefinitionAssignment_0");
					put(grammarAccess.getSqmlTypeReferenceAccess().getTypeParametersAssignment_1_1(), "rule__SqmlTypeReference__TypeParametersAssignment_1_1");
					put(grammarAccess.getSqmlTypeReferenceAccess().getTypeParametersAssignment_1_2_1(), "rule__SqmlTypeReference__TypeParametersAssignment_1_2_1");
					put(grammarAccess.getSqmlTypeReferenceAccess().getListAssignment_2_0(), "rule__SqmlTypeReference__ListAssignment_2_0");
					put(grammarAccess.getSqmlValueTypeAccess().getNameAssignment_1(), "rule__SqmlValueType__NameAssignment_1");
					put(grammarAccess.getSqmlEnumAccess().getNameAssignment_1(), "rule__SqmlEnum__NameAssignment_1");
					put(grammarAccess.getSqmlEnumAccess().getTypeReferenceAssignment_2_1(), "rule__SqmlEnum__TypeReferenceAssignment_2_1");
					put(grammarAccess.getSqmlEnumAccess().getEnumeratorsAssignment_4(), "rule__SqmlEnum__EnumeratorsAssignment_4");
					put(grammarAccess.getSqmlEnumeratorAccess().getNameAssignment_0(), "rule__SqmlEnumerator__NameAssignment_0");
					put(grammarAccess.getSqmlEnumeratorAccess().getValueAssignment_1_1(), "rule__SqmlEnumerator__ValueAssignment_1_1");
					put(grammarAccess.getSqmlTableAccess().getEnumTableAssignment_0(), "rule__SqmlTable__EnumTableAssignment_0");
					put(grammarAccess.getSqmlTableAccess().getNameAssignment_2(), "rule__SqmlTable__NameAssignment_2");
					put(grammarAccess.getSqmlTableAccess().getPhysicalNameOverrideAssignment_3(), "rule__SqmlTable__PhysicalNameOverrideAssignment_3");
					put(grammarAccess.getSqmlTableAccess().getColumnsAssignment_5(), "rule__SqmlTable__ColumnsAssignment_5");
					put(grammarAccess.getSqmlTableAccess().getTableKeysAssignment_6(), "rule__SqmlTable__TableKeysAssignment_6");
					put(grammarAccess.getSqmlTableAccess().getEnumsAssignment_7(), "rule__SqmlTable__EnumsAssignment_7");
					put(grammarAccess.getSqmlTableAccess().getRowsAssignment_8(), "rule__SqmlTable__RowsAssignment_8");
					put(grammarAccess.getSqmlTableColumnAccess().getPrimaryKeyAssignment_0(), "rule__SqmlTableColumn__PrimaryKeyAssignment_0");
					put(grammarAccess.getSqmlTableColumnAccess().getTypeReferenceAssignment_1(), "rule__SqmlTableColumn__TypeReferenceAssignment_1");
					put(grammarAccess.getSqmlTableColumnAccess().getNameAssignment_2(), "rule__SqmlTableColumn__NameAssignment_2");
					put(grammarAccess.getSqmlTableColumnAccess().getDefaultValueAssignment_3_1_0(), "rule__SqmlTableColumn__DefaultValueAssignment_3_1_0");
					put(grammarAccess.getSqmlTableColumnAccess().getDefaultNullAssignment_3_1_1(), "rule__SqmlTableColumn__DefaultNullAssignment_3_1_1");
					put(grammarAccess.getSqmlTableColumnAccess().getDefaultNowAssignment_3_1_2(), "rule__SqmlTableColumn__DefaultNowAssignment_3_1_2");
					put(grammarAccess.getSqmlTableColumnAccess().getSerialAssignment_3_1_3(), "rule__SqmlTableColumn__SerialAssignment_3_1_3");
					put(grammarAccess.getSqmlTableColumnAccess().getBaseColumnAssignment_3_1_4(), "rule__SqmlTableColumn__BaseColumnAssignment_3_1_4");
					put(grammarAccess.getSqmlTableColumnAccess().getNullableAssignment_4_1_0(), "rule__SqmlTableColumn__NullableAssignment_4_1_0");
					put(grammarAccess.getSqmlTableColumnAccess().getTimestampAssignment_4_1_1(), "rule__SqmlTableColumn__TimestampAssignment_4_1_1");
					put(grammarAccess.getSqmlTableColumnAccess().getUnsignedAssignment_4_1_2(), "rule__SqmlTableColumn__UnsignedAssignment_4_1_2");
					put(grammarAccess.getSqmlTableColumnAccess().getOnDeleteActionAssignment_4_1_3_2(), "rule__SqmlTableColumn__OnDeleteActionAssignment_4_1_3_2");
					put(grammarAccess.getSqmlTableColumnAccess().getOnUpdateActionAssignment_4_1_4_2(), "rule__SqmlTableColumn__OnUpdateActionAssignment_4_1_4_2");
					put(grammarAccess.getSqmlTableColumnAccess().getOnUpdateNowAssignment_4_1_5_2(), "rule__SqmlTableColumn__OnUpdateNowAssignment_4_1_5_2");
					put(grammarAccess.getSqmlTableColumnAccess().getPhysicalNameOverrideAssignment_4_1_6(), "rule__SqmlTableColumn__PhysicalNameOverrideAssignment_4_1_6");
					put(grammarAccess.getSqmlTableColumnAccess().getBitsAssignment_4_1_7_2(), "rule__SqmlTableColumn__BitsAssignment_4_1_7_2");
					put(grammarAccess.getSqmlTableColumnAccess().getPrecisionAssignment_4_1_8_2(), "rule__SqmlTableColumn__PrecisionAssignment_4_1_8_2");
					put(grammarAccess.getSqmlTableColumnAccess().getScaleAssignment_4_1_8_4(), "rule__SqmlTableColumn__ScaleAssignment_4_1_8_4");
					put(grammarAccess.getSqmlTableColumnAccess().getMaxLengthAssignment_4_1_9_2(), "rule__SqmlTableColumn__MaxLengthAssignment_4_1_9_2");
					put(grammarAccess.getSqmlTableColumnAccess().getLengthBitsAssignment_4_1_10_2(), "rule__SqmlTableColumn__LengthBitsAssignment_4_1_10_2");
					put(grammarAccess.getSqmlTableColumnAccess().getCharacterSetAssignment_4_1_11_3(), "rule__SqmlTableColumn__CharacterSetAssignment_4_1_11_3");
					put(grammarAccess.getSqmlTableColumnAccess().getCollationAssignment_4_1_12_2(), "rule__SqmlTableColumn__CollationAssignment_4_1_12_2");
					put(grammarAccess.getSqmlTableColumnAccess().getCommentAssignment_4_1_13_2(), "rule__SqmlTableColumn__CommentAssignment_4_1_13_2");
					put(grammarAccess.getSqmlTableColumnAccess().getConstraintNameAssignment_4_1_14_2(), "rule__SqmlTableColumn__ConstraintNameAssignment_4_1_14_2");
					put(grammarAccess.getSqmlTableRowAccess().getValuesAssignment_2(), "rule__SqmlTableRow__ValuesAssignment_2");
					put(grammarAccess.getSqmlTableRowAccess().getValuesAssignment_3_1(), "rule__SqmlTableRow__ValuesAssignment_3_1");
					put(grammarAccess.getSqmlTableRowValueAccess().getLiteralAssignment_0(), "rule__SqmlTableRowValue__LiteralAssignment_0");
					put(grammarAccess.getSqmlTableRowValueAccess().getNullAssignment_1(), "rule__SqmlTableRowValue__NullAssignment_1");
					put(grammarAccess.getSqmlRowConstructorDefaultValueAccess().getValueReferencesAssignment_2_0(), "rule__SqmlRowConstructorDefaultValue__ValueReferencesAssignment_2_0");
					put(grammarAccess.getSqmlRowConstructorDefaultValueAccess().getValueReferencesAssignment_2_1_1(), "rule__SqmlRowConstructorDefaultValue__ValueReferencesAssignment_2_1_1");
					put(grammarAccess.getSqmlLiteralDefaultValueAccess().getMinusAssignment_0(), "rule__SqmlLiteralDefaultValue__MinusAssignment_0");
					put(grammarAccess.getSqmlLiteralDefaultValueAccess().getLiteralAssignment_1(), "rule__SqmlLiteralDefaultValue__LiteralAssignment_1");
					put(grammarAccess.getSqmlValueReferenceDefaultValueAccess().getValueReferenceAssignment(), "rule__SqmlValueReferenceDefaultValue__ValueReferenceAssignment");
					put(grammarAccess.getSqmlTableKeyAccess().getColumnsAssignment_1(), "rule__SqmlTableKey__ColumnsAssignment_1");
					put(grammarAccess.getSqmlTableKeyAccess().getNameAssignment_2_1(), "rule__SqmlTableKey__NameAssignment_2_1");
					put(grammarAccess.getSqmlQueryAccess().getNameAssignment_1(), "rule__SqmlQuery__NameAssignment_1");
					put(grammarAccess.getSqmlQueryAccess().getParametersAssignment_3(), "rule__SqmlQuery__ParametersAssignment_3");
					put(grammarAccess.getSqmlQueryAccess().getSelectAssignment_4(), "rule__SqmlQuery__SelectAssignment_4");
					put(grammarAccess.getSqmlQueryParameterAccess().getOptionalAssignment_0(), "rule__SqmlQueryParameter__OptionalAssignment_0");
					put(grammarAccess.getSqmlQueryParameterAccess().getTypeReferenceAssignment_1(), "rule__SqmlQueryParameter__TypeReferenceAssignment_1");
					put(grammarAccess.getSqmlQueryParameterAccess().getNameAssignment_2(), "rule__SqmlQueryParameter__NameAssignment_2");
					put(grammarAccess.getSqmlFunctionAccess().getReturnTypeAssignment_1(), "rule__SqmlFunction__ReturnTypeAssignment_1");
					put(grammarAccess.getSqmlFunctionAccess().getNameAssignment_2(), "rule__SqmlFunction__NameAssignment_2");
					put(grammarAccess.getSqmlFunctionAccess().getParametersAssignment_4_0(), "rule__SqmlFunction__ParametersAssignment_4_0");
					put(grammarAccess.getSqmlFunctionAccess().getParametersAssignment_4_1_1(), "rule__SqmlFunction__ParametersAssignment_4_1_1");
					put(grammarAccess.getSqmlFunctionAccess().getExpressionAssignment_7_0(), "rule__SqmlFunction__ExpressionAssignment_7_0");
					put(grammarAccess.getSqmlFunctionAccess().getSqlAssignment_7_1_1(), "rule__SqmlFunction__SqlAssignment_7_1_1");
					put(grammarAccess.getSqmlFunctionParameterAccess().getTypeReferenceAssignment_0(), "rule__SqmlFunctionParameter__TypeReferenceAssignment_0");
					put(grammarAccess.getSqmlFunctionParameterAccess().getNameAssignment_1(), "rule__SqmlFunctionParameter__NameAssignment_1");
					put(grammarAccess.getSqmlSqlAccess().getTokensAssignment_2(), "rule__SqmlSql__TokensAssignment_2");
					put(grammarAccess.getSqmlSqlKeywordAccess().getKeywordTextAssignment(), "rule__SqmlSqlKeyword__KeywordTextAssignment");
					put(grammarAccess.getSqmlSqlIdAccess().getIdentifierAssignment(), "rule__SqmlSqlId__IdentifierAssignment");
					put(grammarAccess.getSqmlSqlSymbolAccess().getSymbolTextAssignment(), "rule__SqmlSqlSymbol__SymbolTextAssignment");
					put(grammarAccess.getSqmlSqlStringLiteralAccess().getStringAssignment(), "rule__SqmlSqlStringLiteral__StringAssignment");
					put(grammarAccess.getSqmlSqlNumberLiteralAccess().getIntegerAssignment_0(), "rule__SqmlSqlNumberLiteral__IntegerAssignment_0");
					put(grammarAccess.getSqmlSqlNumberLiteralAccess().getDecimalAssignment_1(), "rule__SqmlSqlNumberLiteral__DecimalAssignment_1");
					put(grammarAccess.getSqmlSelectAccess().getPartsAssignment(), "rule__SqmlSelect__PartsAssignment");
					put(grammarAccess.getSqmlSelectIfAccess().getConditionAssignment_2(), "rule__SqmlSelectIf__ConditionAssignment_2");
					put(grammarAccess.getSqmlSelectIfAccess().getPartsAssignment_4(), "rule__SqmlSelectIf__PartsAssignment_4");
					put(grammarAccess.getSqmlSelectIfAccess().getElseIfsAssignment_6(), "rule__SqmlSelectIf__ElseIfsAssignment_6");
					put(grammarAccess.getSqmlSelectIfAccess().getElseAssignment_7(), "rule__SqmlSelectIf__ElseAssignment_7");
					put(grammarAccess.getSqmlSelectElseIfAccess().getConditionAssignment_2(), "rule__SqmlSelectElseIf__ConditionAssignment_2");
					put(grammarAccess.getSqmlSelectElseIfAccess().getPartsAssignment_4(), "rule__SqmlSelectElseIf__PartsAssignment_4");
					put(grammarAccess.getSqmlSelectElseAccess().getPartsAssignment_3(), "rule__SqmlSelectElse__PartsAssignment_3");
					put(grammarAccess.getSqmlSelectClauseAccess().getDistinctAssignment_1(), "rule__SqmlSelectClause__DistinctAssignment_1");
					put(grammarAccess.getSqmlSelectClauseAccess().getColumnsAssignment_2(), "rule__SqmlSelectClause__ColumnsAssignment_2");
					put(grammarAccess.getSqmlSelectClauseAccess().getColumnsAssignment_3_1(), "rule__SqmlSelectClause__ColumnsAssignment_3_1");
					put(grammarAccess.getSqmlSelectColumnAccess().getExpressionAssignment_0(), "rule__SqmlSelectColumn__ExpressionAssignment_0");
					put(grammarAccess.getSqmlSelectColumnAccess().getAliasAssignment_1_1(), "rule__SqmlSelectColumn__AliasAssignment_1_1");
					put(grammarAccess.getSqmlSelectColumnAccess().getTitleAssignment_2_1(), "rule__SqmlSelectColumn__TitleAssignment_2_1");
					put(grammarAccess.getSqmlFromClauseAccess().getVariableAssignment_1(), "rule__SqmlFromClause__VariableAssignment_1");
					put(grammarAccess.getSqmlForeignKeyVariableAccess().getVariableAssignment_0(), "rule__SqmlForeignKeyVariable__VariableAssignment_0");
					put(grammarAccess.getSqmlForeignKeyVariableAccess().getColumnAssignment_2(), "rule__SqmlForeignKeyVariable__ColumnAssignment_2");
					put(grammarAccess.getSqmlForeignKeyVariableAccess().getNameAssignment_4(), "rule__SqmlForeignKeyVariable__NameAssignment_4");
					put(grammarAccess.getSqmlTableVariableAccess().getTableAssignment_0(), "rule__SqmlTableVariable__TableAssignment_0");
					put(grammarAccess.getSqmlTableVariableAccess().getNameAssignment_2(), "rule__SqmlTableVariable__NameAssignment_2");
					put(grammarAccess.getSqmlSubSelectVariableAccess().getSubSelectAssignment_1(), "rule__SqmlSubSelectVariable__SubSelectAssignment_1");
					put(grammarAccess.getSqmlSubSelectVariableAccess().getNameAssignment_4(), "rule__SqmlSubSelectVariable__NameAssignment_4");
					put(grammarAccess.getSqmlJoinClauseAccess().getLeftJoinAssignment_0(), "rule__SqmlJoinClause__LeftJoinAssignment_0");
					put(grammarAccess.getSqmlJoinClauseAccess().getVariableAssignment_2(), "rule__SqmlJoinClause__VariableAssignment_2");
					put(grammarAccess.getSqmlJoinClauseAccess().getConditionsAssignment_3_1(), "rule__SqmlJoinClause__ConditionsAssignment_3_1");
					put(grammarAccess.getSqmlWhereClauseAccess().getConditionAssignment_1(), "rule__SqmlWhereClause__ConditionAssignment_1");
					put(grammarAccess.getSqmlGroupByClauseAccess().getExpressionsAssignment_2(), "rule__SqmlGroupByClause__ExpressionsAssignment_2");
					put(grammarAccess.getSqmlGroupByClauseAccess().getExpressionsAssignment_3_1(), "rule__SqmlGroupByClause__ExpressionsAssignment_3_1");
					put(grammarAccess.getSqmlHavingClauseAccess().getConditionAssignment_1(), "rule__SqmlHavingClause__ConditionAssignment_1");
					put(grammarAccess.getSqmlOrderByClauseAccess().getExpressionsAssignment_2(), "rule__SqmlOrderByClause__ExpressionsAssignment_2");
					put(grammarAccess.getSqmlOrderByClauseAccess().getExpressionsAssignment_3_1(), "rule__SqmlOrderByClause__ExpressionsAssignment_3_1");
					put(grammarAccess.getSqmlOrderByExpressionAccess().getExpressionAssignment_0(), "rule__SqmlOrderByExpression__ExpressionAssignment_0");
					put(grammarAccess.getSqmlOrderByExpressionAccess().getDescendingAssignment_1_1(), "rule__SqmlOrderByExpression__DescendingAssignment_1_1");
					put(grammarAccess.getSqmlOrAccess().getRightAssignment_1_2(), "rule__SqmlOr__RightAssignment_1_2");
					put(grammarAccess.getSqmlAndAccess().getRightAssignment_1_2(), "rule__SqmlAnd__RightAssignment_1_2");
					put(grammarAccess.getSqmlConditionAccess().getConditionAssignment_0_2(), "rule__SqmlCondition__ConditionAssignment_0_2");
					put(grammarAccess.getSqmlConditionAccess().getSubSelectAssignment_1_2(), "rule__SqmlCondition__SubSelectAssignment_1_2");
					put(grammarAccess.getSqmlConditionAccess().getFunctionAssignment_2_1_0_1(), "rule__SqmlCondition__FunctionAssignment_2_1_0_1");
					put(grammarAccess.getSqmlConditionAccess().getRightAssignment_2_1_0_2(), "rule__SqmlCondition__RightAssignment_2_1_0_2");
					put(grammarAccess.getSqmlConditionAccess().getNotAssignment_2_1_1_1(), "rule__SqmlCondition__NotAssignment_2_1_1_1");
					put(grammarAccess.getSqmlConditionAccess().getRightAssignment_2_1_1_3(), "rule__SqmlCondition__RightAssignment_2_1_1_3");
					put(grammarAccess.getSqmlConditionAccess().getEscapeAssignment_2_1_1_4_1(), "rule__SqmlCondition__EscapeAssignment_2_1_1_4_1");
					put(grammarAccess.getSqmlConditionAccess().getNotAssignment_2_1_2_2(), "rule__SqmlCondition__NotAssignment_2_1_2_2");
					put(grammarAccess.getSqmlConditionAccess().getLeftAssignment_2_1_3_2(), "rule__SqmlCondition__LeftAssignment_2_1_3_2");
					put(grammarAccess.getSqmlConditionAccess().getRightAssignment_2_1_3_4(), "rule__SqmlCondition__RightAssignment_2_1_3_4");
					put(grammarAccess.getSqmlConditionAccess().getNotAssignment_2_1_4_1(), "rule__SqmlCondition__NotAssignment_2_1_4_1");
					put(grammarAccess.getSqmlConditionAccess().getRightAssignment_2_1_4_3(), "rule__SqmlCondition__RightAssignment_2_1_4_3");
					put(grammarAccess.getSqmlConditionAccess().getNotAssignment_2_1_5_1(), "rule__SqmlCondition__NotAssignment_2_1_5_1");
					put(grammarAccess.getSqmlConditionAccess().getRegexpAssignment_2_1_5_3(), "rule__SqmlCondition__RegexpAssignment_2_1_5_3");
					put(grammarAccess.getSqmlAdditionAccess().getFunctionAssignment_1_1(), "rule__SqmlAddition__FunctionAssignment_1_1");
					put(grammarAccess.getSqmlAdditionAccess().getRightAssignment_1_2(), "rule__SqmlAddition__RightAssignment_1_2");
					put(grammarAccess.getSqmlMultiplicationAccess().getFunctionAssignment_1_1(), "rule__SqmlMultiplication__FunctionAssignment_1_1");
					put(grammarAccess.getSqmlMultiplicationAccess().getRightAssignment_1_2(), "rule__SqmlMultiplication__RightAssignment_1_2");
					put(grammarAccess.getSqmlSubSelectAccess().getSelectAssignment_1(), "rule__SqmlSubSelect__SelectAssignment_1");
					put(grammarAccess.getSqmlStaticVariableReferenceAccess().getNextIterationAssignment_0(), "rule__SqmlStaticVariableReference__NextIterationAssignment_0");
					put(grammarAccess.getSqmlStaticVariableReferenceAccess().getVariableAssignment_2(), "rule__SqmlStaticVariableReference__VariableAssignment_2");
					put(grammarAccess.getSqmlRowConstructorAccess().getExplicitAssignment_0(), "rule__SqmlRowConstructor__ExplicitAssignment_0");
					put(grammarAccess.getSqmlRowConstructorAccess().getExpressionsAssignment_2(), "rule__SqmlRowConstructor__ExpressionsAssignment_2");
					put(grammarAccess.getSqmlRowConstructorAccess().getExpressionsAssignment_3_1(), "rule__SqmlRowConstructor__ExpressionsAssignment_3_1");
					put(grammarAccess.getSqmlNegationAccess().getExpressionAssignment_1(), "rule__SqmlNegation__ExpressionAssignment_1");
					put(grammarAccess.getSqmlFunctionCallAccess().getFunctionAssignment_0(), "rule__SqmlFunctionCall__FunctionAssignment_0");
					put(grammarAccess.getSqmlFunctionCallAccess().getArgumentsAssignment_2_0(), "rule__SqmlFunctionCall__ArgumentsAssignment_2_0");
					put(grammarAccess.getSqmlFunctionCallAccess().getArgumentsAssignment_2_1_1(), "rule__SqmlFunctionCall__ArgumentsAssignment_2_1_1");
					put(grammarAccess.getSqmlGroupConcatAccess().getDistinctAssignment_2(), "rule__SqmlGroupConcat__DistinctAssignment_2");
					put(grammarAccess.getSqmlGroupConcatAccess().getExpressionsAssignment_3(), "rule__SqmlGroupConcat__ExpressionsAssignment_3");
					put(grammarAccess.getSqmlGroupConcatAccess().getExpressionsAssignment_4_1(), "rule__SqmlGroupConcat__ExpressionsAssignment_4_1");
					put(grammarAccess.getSqmlGroupConcatAccess().getOrderByExpressionsAssignment_5_2(), "rule__SqmlGroupConcat__OrderByExpressionsAssignment_5_2");
					put(grammarAccess.getSqmlGroupConcatAccess().getOrderByExpressionsAssignment_5_3_1(), "rule__SqmlGroupConcat__OrderByExpressionsAssignment_5_3_1");
					put(grammarAccess.getSqmlGroupConcatAccess().getSeparatorAssignment_6_1(), "rule__SqmlGroupConcat__SeparatorAssignment_6_1");
					put(grammarAccess.getSqmlCaseAccess().getOperandAssignment_1(), "rule__SqmlCase__OperandAssignment_1");
					put(grammarAccess.getSqmlCaseAccess().getWhensAssignment_2(), "rule__SqmlCase__WhensAssignment_2");
					put(grammarAccess.getSqmlCaseAccess().getElseExpressionAssignment_3_1(), "rule__SqmlCase__ElseExpressionAssignment_3_1");
					put(grammarAccess.getSqmlCaseWhenAccess().getWhenExpressionAssignment_1(), "rule__SqmlCaseWhen__WhenExpressionAssignment_1");
					put(grammarAccess.getSqmlCaseWhenAccess().getThenExpressionAssignment_3(), "rule__SqmlCaseWhen__ThenExpressionAssignment_3");
					put(grammarAccess.getSqmlIfAccess().getConditionAssignment_2(), "rule__SqmlIf__ConditionAssignment_2");
					put(grammarAccess.getSqmlIfAccess().getThenExpressionAssignment_4(), "rule__SqmlIf__ThenExpressionAssignment_4");
					put(grammarAccess.getSqmlIfAccess().getElseExpressionAssignment_6(), "rule__SqmlIf__ElseExpressionAssignment_6");
					put(grammarAccess.getSqmlIfNullAccess().getTestExpressionAssignment_2(), "rule__SqmlIfNull__TestExpressionAssignment_2");
					put(grammarAccess.getSqmlIfNullAccess().getThenExpressionAssignment_4(), "rule__SqmlIfNull__ThenExpressionAssignment_4");
					put(grammarAccess.getSqmlStaticIfAccess().getConditionsAssignment_2(), "rule__SqmlStaticIf__ConditionsAssignment_2");
					put(grammarAccess.getSqmlStaticIfAccess().getExpressionsAssignment_4(), "rule__SqmlStaticIf__ExpressionsAssignment_4");
					put(grammarAccess.getSqmlStaticIfAccess().getConditionsAssignment_6_1(), "rule__SqmlStaticIf__ConditionsAssignment_6_1");
					put(grammarAccess.getSqmlStaticIfAccess().getExpressionsAssignment_6_3(), "rule__SqmlStaticIf__ExpressionsAssignment_6_3");
					put(grammarAccess.getSqmlStaticIfAccess().getElseExpressionAssignment_7_2(), "rule__SqmlStaticIf__ElseExpressionAssignment_7_2");
					put(grammarAccess.getSqmlStaticOrAccess().getRightAssignment_1_2(), "rule__SqmlStaticOr__RightAssignment_1_2");
					put(grammarAccess.getSqmlStaticAndAccess().getRightAssignment_1_2(), "rule__SqmlStaticAnd__RightAssignment_1_2");
					put(grammarAccess.getSqmlStaticIsEmptyAccess().getParameterReferenceAssignment_0(), "rule__SqmlStaticIsEmpty__ParameterReferenceAssignment_0");
					put(grammarAccess.getSqmlStaticIsEmptyAccess().getNotAssignment_2(), "rule__SqmlStaticIsEmpty__NotAssignment_2");
					put(grammarAccess.getSqmlStaticIsNullAccess().getParameterReferenceAssignment_0(), "rule__SqmlStaticIsNull__ParameterReferenceAssignment_0");
					put(grammarAccess.getSqmlStaticIsNullAccess().getNotAssignment_2(), "rule__SqmlStaticIsNull__NotAssignment_2");
					put(grammarAccess.getSqmlStaticIsTrueAccess().getNotAssignment_0(), "rule__SqmlStaticIsTrue__NotAssignment_0");
					put(grammarAccess.getSqmlStaticIsTrueAccess().getParameterReferenceAssignment_1(), "rule__SqmlStaticIsTrue__ParameterReferenceAssignment_1");
					put(grammarAccess.getSqmlStaticParenthesesAccess().getExpressionAssignment_1(), "rule__SqmlStaticParentheses__ExpressionAssignment_1");
					put(grammarAccess.getSqmlValueReferenceAccess().getNextIterationAssignment_0(), "rule__SqmlValueReference__NextIterationAssignment_0");
					put(grammarAccess.getSqmlValueReferenceAccess().getPathAssignment_1(), "rule__SqmlValueReference__PathAssignment_1");
					put(grammarAccess.getSqmlValueReferenceAccess().getDotStarAssignment_2(), "rule__SqmlValueReference__DotStarAssignment_2");
					put(grammarAccess.getSqmlPathAccess().getTargetAssignment_0(), "rule__SqmlPath__TargetAssignment_0");
					put(grammarAccess.getSqmlPathAccess().getTargetAssignment_1_2(), "rule__SqmlPath__TargetAssignment_1_2");
					put(grammarAccess.getSqmlIntegerLiteralAccess().getValueAssignment(), "rule__SqmlIntegerLiteral__ValueAssignment");
					put(grammarAccess.getSqmlLongLiteralAccess().getValueAssignment(), "rule__SqmlLongLiteral__ValueAssignment");
					put(grammarAccess.getSqmlFloatLiteralAccess().getValueAssignment(), "rule__SqmlFloatLiteral__ValueAssignment");
					put(grammarAccess.getSqmlDoubleLiteralAccess().getValueAssignment(), "rule__SqmlDoubleLiteral__ValueAssignment");
					put(grammarAccess.getSqmlDecimalLiteralAccess().getValueAssignment(), "rule__SqmlDecimalLiteral__ValueAssignment");
					put(grammarAccess.getSqmlStringLiteralAccess().getValueAssignment(), "rule__SqmlStringLiteral__ValueAssignment");
					put(grammarAccess.getSqmlBooleanLiteralAccess().getTrueAssignment_0_1(), "rule__SqmlBooleanLiteral__TrueAssignment_0_1");
					put(grammarAccess.getSqmlTableColumnAccess().getUnorderedGroup_4_1(), "rule__SqmlTableColumn__UnorderedGroup_4_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.softicar.sqml.ui.contentassist.antlr.internal.InternalSqmlParser typedParser = (com.softicar.sqml.ui.contentassist.antlr.internal.InternalSqmlParser) parser;
			typedParser.entryRuleSqmlFile();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SqmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SqmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
