/*
 * generated by Xtext
 */
package com.softicar.sqml.ui.tests;

import com.google.inject.Injector;
import com.softicar.sqml.ui.internal.SqmlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SqmlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SqmlActivator.getInstance().getInjector("com.softicar.sqml.Sqml");
	}

}
