/*
 * generated by Xtext
 */
package com.softicar.sqml.parser.antlr;

import com.google.inject.Inject;
import com.softicar.sqml.parser.antlr.internal.InternalSqmlParser;
import com.softicar.sqml.services.SqmlGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SqmlParser extends AbstractAntlrParser {

	@Inject
	private SqmlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSqmlParser createParser(XtextTokenStream stream) {
		return new InternalSqmlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SqmlFile";
	}

	public SqmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SqmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
