/*
 * generated by Xtext
 */
package com.softicar.sqml.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.softicar.sqml.ui.internal.SqmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SqmlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SqmlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SqmlActivator.getInstance().getInjector(SqmlActivator.COM_SOFTICAR_SQML_SQML);
	}
	
}
