/*
 * generated by Xtext
 */
package com.softicar.sqml.ui;

import com.google.inject.Injector;
import com.softicar.sqml.ui.internal.SqmlActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SqmlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SqmlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SqmlActivator activator = SqmlActivator.getInstance();
		return activator != null ? activator.getInjector(SqmlActivator.COM_SOFTICAR_SQML_SQML) : null;
	}

}
