/*
 * generated by Xtext
 */
package com.softicar.sqml.ui.outline;

/**
 * Customization of the default outline structure. see
 * http://www.eclipse.org/Xtext/documentation.html#outline
 */
public class SqmlOutlineTreeProvider extends org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider {

	// nothing to add, yet
}
