/*
 * generated by Xtext
 */
package com.softicar.sqml;

import org.eclipse.xtext.testing.IInjectorProvider;

import com.google.inject.Injector;

public class SqmlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return com.softicar.sqml.ui.internal.SqmlActivator.getInstance().getInjector("com.softicar.sqml.Sqml");
	}

}
